name: Brew tests impl

on:
  workflow_call:

jobs:
  build_linuxbrew:
    name: Build on linxbrew
    runs-on: ubuntu-latest
    container: homebrew/brew:latest
    steps:
      - name: Checkout mamba repository
        uses: actions/checkout@v1

      - name: Install prerequisites
        run: brew install fmt libarchive libsolv lz4 openssl@3 reproc simdjson xz yaml-cpp zstd cmake cli11 nlohmann-json spdlog tl-expected curl pkgconfig python

      - name: Configure
        run: cmake -S. -Bbuild -DBUILD_LIBMAMBA=ON -DBUILD_MAMBA=ON -DBUILD_SHARED=ON -DBUILD_STATIC=OFF

      - name: Build
        run: cmake --build build -j4
